[config]
default_to_workspace = false

[tasks.slang]
script_runner = "@shell"
script = '''
cd karaokeparty
# Generate structured language files
dart run slang
# Checks missing and unused translations
dart run slang analyze
'''

[tasks.build-flutter]
dependencies = ["slang"]
script_runner = "@shell"
script = '''
cd karaokeparty
flutter build web --release --wasm
'''

[tasks.build-server]
command = "cargo"
args = ["build", "--bin", "karaoke-server", "--release"]

[tasks.serve]
command = "cargo"
args = ["run", "--bin", "karaoke-server", "--", "-c", "config.example.yaml"]

[tasks.import]
command = "cargo"
args = [
    "run",
    "--bin",
    "importer",
    "--",
    "--db",
    "songs.db",
    "-s",
    "6",
    "MasterCollection/Songs",
]
