name: karaokeparty
description: "Client for the Karaoke-Server."
publish_to: "none"

version: 1.1.5+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  animated_list_plus: ^0.5.2
  audioplayers: ^6.5.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_constraintlayout: ^1.7.0-stable
  flutter_slidable: ^4.0.0
  http: ^1.5.0
  hydrated_bloc: ^10.1.1
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.20.2
  logger: ^2.6.1
  path_provider: ^2.1.5
  rounded_loading_button_plus: ^3.0.1
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0+1
  slang: ^4.8.1
  timer_builder: ^2.0.0
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  slang_flutter: ^4.8.0
  slang_build_runner: ^4.8.1

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
