name: karaokeparty
description: "Client for the Karaoke-Server."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  animated_list_plus: ^0.5.2
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_constraintlayout: ^1.7.0-stable
  flutter_slidable: ^3.0.1
  http: ^1.1.2
  hydrated_bloc: ^9.1.5
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  path_provider: ^2.1.2
  rounded_loading_button: ^2.1.0
  shared_preferences: ^2.2.2
  skeletonizer: ^1.1.1
  slang: ^3.28.0
  timer_builder: ^2.0.0
  uuid: ^4.2.2
  web_socket_channel: ^2.4.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  slang_flutter: ^3.17.0
  slang_build_runner: ^3.17.0

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
